name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup ndroid SDK
      uses: android-actions/setup-android@v3
      with:
          sdk-platform: '34'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload Release APK
      uses: actions/upload-artifact@v2
      with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
